### ISSUE TITLE
font-size < 10px doesn't work `em` on Chrome

### ISSUE THREAD

**Issue by BcRikko** [nostalgic-css/NES.css#262]
**Describe the bug**
Does not see icons less than 10px on Chrome.

**Expected behavior**

**Screenshots**
![2019-01-29 17 48 49](https://user-images.githubusercontent.com/5305599/51895900-9aee2e00-23ee-11e9-8091-0910b53ea7a6.png)

**Environment:**
 - OS: macOS High Sierra
 - Browser: Chrome 71

**Suggestion(s) for fixing this issue**

Use `transform: scale(xx)` instead of `em`.

```scss
.nes-icon {
  &.is-small {
    transform: scale(0.5);
  }
  &.is-medium {
    transform: scale(1.5);
  }
  &.is-large {
    transform: scale(2);
  }
  &.heart {
    @include pixelize(...);
  }
}
```
