### ISSUE TITLE
Bug: Code format on Documentation site

### ISSUE THREAD

**Issue by samzeng** [nostalgic-css/NES.css#298]
**Describe the bug**
Code format in the code demo div.

**To Reproduce**
01. Open [documentation demo website](https://nostalgic-css.github.io/NES.css/);
02. Click on the "show code button".

**Expected behavior**
![expected](https://user-images.githubusercontent.com/2367250/53161551-29785880-3605-11e9-8eaa-38408acee401.png)

**Screenshots**
![screenshots](https://user-images.githubusercontent.com/2367250/53161563-3006d000-3605-11e9-860c-dcaeff3e0121.png)

**Environment:**
 - OS: Windows 10 Pro
 - Browser: Chrome v72.0.3626.81 64-bits
 - Build environment (i.e. NodeJS): N/A

**Suggestion(s) for fixing this issue**
https://github.com/nostalgic-css/NES.css/blob/develop/demo/style.css#L112

```css
.sample-code > code {
  display: block; /* add this code */
  padding: 1em 2em; /* padding not working inline element */
  line-height: 2em;
}
```

Result:
![toggle-fixed](https://user-images.githubusercontent.com/2367250/53162022-1c0f9e00-3606-11e9-93f0-44b2df4adde9.gif)

**Additional context**
N/A
