### ISSUE TITLE
NES.css@next

### ISSUE THREAD

**Issue by BcRikko** [nostalgic-css/NES.css#331]
**Is your feature request related to a problem? Please describe.**

I want a flexible CSS framework using CSS Variables.

**Describe the solution you'd like**

NES.css is inconvenient.
For example, If I want to use NES.css in a **Dark Theme**.
The border color, background-color, etc. are different from the color I'm looking for.

**Describe alternatives you've considered**

```html
<!-- default theme -->
<button class="nes-btn"></button>

<!-- my theme -->
<button class="nes-btn my-theme"></button>
```

```css
/* Default theme */
:root {
  --bg-color: white;
  --border-color: black;
  --color: black; 
}

.is-primary { /**/ }
.is-success { /**/ }
.is-warning { /**/ }
.is-error { /**/ }

/* My theme */
.my-theme {
  --bg-color: black;
  --bordor-color: green;
  --color: green;
}

.nes-btn {
  background-color: var(--bg-color);
  border-color: var(--border-color);
  color: var(--color);
}
```
<img width="311" alt="スクリーンショット 2019-05-05 9 54 04" src="https://user-images.githubusercontent.com/5305599/57186526-bc921080-6f1b-11e9-8696-e3bdc04a9b86.png">

But IE does not support CSS Variables. 😢 
https://caniuse.com/#feat=css-variables

**Comment by thisconnect** [comment]
> But IE does not support CSS Variables. 😢
> If you want IE support, you need a polyfill.
> https://caniuse.com/#feat=css-variables

NES.css shouldn't have a polyfill, if you want to support IE11 you can use something like nextcss or postcss-preset-env to render css variables to support IE11

**Comment by BcRikko** [comment]
> NES.css shouldn't have a polyfill

Sure. I agree. 👍 

I don't intend to support IE11 on NES.css. 🤔 
Because Windows 7 will no longer be supported in 2020. Then, IE11 will disappear from Windows.
If you need to support IE 11, you can use NES.css with polyfill or nextcss, postcss. 😆🔧

**Comment by BcRikko** [comment]
```html
<section class="nes-container">
  <button class="nes-btn">default</button>
  <button class="nes-btn is-dark">dark</button>
  <button class="nes-btn is-primary">primary</button>
</section>

<!-- <section data-theme="dark"> -->
<section class="nes-container is-dark">
  <button class="nes-btn is-default">default</button>
  <button class="nes-btn">dark</button>
  <button class="nes-btn is-primary">primary</button>
</section>
```

```css
:root, .is-default {
  --bd-color: #333;
  --bg-color: #e4e4e4;
  --color: #333;
}

[data-theme=dark], .is-dark {
  --bd-color: #e4e4e4;
  --bg-color: #333;
  --color: #e4e4e4;
}

.nes-container {
  background-color: var(--bg-color);
  border: solid 5px var(--bd-color);
}

.nes-btn {
  background-color: var(--bg-color);
  color: var(--color);
  border: solid 5px var(--bd-color);
}

.nes-btn.is-primary {
  --bg-color: #1E9CEE;
  --bd-color: #333;
  --color: #e4e4e4;
}
```

![スクリーンショット 2019-06-06 11 08 18](https://user-images.githubusercontent.com/5305599/59001912-6d593b80-884b-11e9-9668-05e5f64895d9.png)

---

It's probably better to specify CSS variables in each element. 🤔 
However, the file size of CSS is likely to increase. 😭
```scss
:root {
  .nes {
    &-btn {
      &-bg-color: #e4e4e4;
      &-color: #333;
    }
    &-container {
      &-bg-color: #e4e4e4;
      &-color: #333;
    }
  }
}
```

**Comment by BcRikko** [comment]
### Structure a scss project
Refer to the SASS The 7-1 Pattern.
https://sass-guidelin.es/#the-7-1-pattern

```
./
|- base
|    |- reboot.scss
|    |- override
|- abstracts
|    |- variables
|    |- utilities
|    |- mixin
|- elements
|- forms
|- icons
|- helpers
|- nes.scss
```

**Comment by BcRikko** [comment]
### 🎨Sharing color theme 

```scss
// Japanese Style Theme
$japanese-apricot: #EAADBD;
$viola-mandshurica: #554562;
$sakura: #FADBE0;

[data-theme=japanese-style] {
  .is-primary {
    --color: $viola-mandshurica;
    --border-color: $viola-mandshurica;
    --background-color: $sakura;
    --shadow-color: $japanese-appricot;
  }
}
```

```html
<html data-theme="japanese-style">
  <head>
    <link href="nes.css" rel="stylesheet" />
    <!-- loading theme file -->
    <link href="nes-theme.japanese-style.css" rel="stylesheet" />
  </head>
  <body>
    <button class="nes-btn is-primary">Reiwa</button>
  </body>
</html>
```

![reiwa-button](https://user-images.githubusercontent.com/5305599/59089476-294a6180-8945-11e9-916c-37eedfec53a4.png)

**Comment by youngkaneda** [comment]
I just disagree with this idea because this allows users use colors that do not fit the nes palette. If i understood right, maybe i'm wrong, this can be used to make components with custom colors.

**Comment by BcRikko** [comment]
Since there is a possibility of conflict CSS Variable names, it's better to prefix variable names. 🤔 

```scss
// `--nes-` + `<property name>`
:root {
  --nes-background-color: $white;
  --nes-color: $black;
}
```

Avvreviations such as `bg` increase the recognition load, so formal property names are better. 👍

**Comment by BcRikko** [comment]
### Why use CSS Custom Properties(CSS Variables)

NES.css is often loaded via the CDN. So many users don't use the Sass variables.
I thought CSS Custom Properties would be the best way to be able to change the theme freely even if it was read via the CDN. 🛠

**Comment by BcRikko** [comment]
Proposal repository 🛠 
https://github.com/BcRikko/NES.css-proposal

**Comment by BcRikko** [comment]
I want to use [dart-sass](https://github.com/sass/dart-sass). 😎 
Because We can use New Sass Module System(`@use` and `@forward`).

## 📚 Examples

### `@use`

```scss
// base/_variables.scss
$font-family: "Press Start 2P" !default;
$font-size: 16px !default;
```

```scss
// base/generic.scss

@use `_variables` as vars;

html {
  font-family: vars.$font-family;
  font-size: vars.$font-size;
}
```

### `@forward`

```scss
// utilties/rounded-corners-mixin.scss

/**
 * private
 */
%rounded-corner-defaults { /****/ }

@mixin border-image($color) { /****/ }

@mixin compact-border-image($color) { /****/ }

@mixin border-image-repeat() { /****/ }

/**
 * public
 */
@mixin rounded-corners($isDark: false) { /****/ }

@mixin compact-rounded-corners($isDark: false) { /****/ }
```

```scss
// utilities/_index.scss
@forward 'rounded-corners-mixin' show rounded-corners, compact-rounded-corners;
```

```scss
@use 'utilities';

.btn {
  // OK
  @include utilities.rounded-corners();
}

.btn {
  // ERROR
  @include utilities.border-image(#fff)
}
```

**Comment by BcRikko** [comment]
CSS nesting in a framework may not be good? 🤔 

For example
```html
<div class="list">
  <div class="item my-custom-color"></div>
</div>
```

```css
/* Bad */
.list > .item {
  color: red;
}

.my-custom-color {
  /* not working, because Specificity of `.list > .item` is high */
  color: blue;
}

/* Alternative */
.list > .item.my-custom-color {
  color: blue;
}

/* or */

.my-custom-color {
  /* but I don't like `!important` */
  color: blue !important;
}
```

```css
/* Better?? */
.list {  }
.list-item {
  color: red;
}

.my-custom-color {
  /* working!! */
  color: blue;
}
```
