### ISSUE TITLE
Support HTML Form Validation pseudo-classes

### ISSUE THREAD

**Issue by astronouth7303** [nostalgic-css/NES.css#356]
**Is your feature request related to a problem? Please describe.**

Currently, the `.is-success` and `.is-error` styles are not triggered by `:valid` and `:invalid`

**Describe the solution you'd like**
`.nes-input:valid` and `.nes-input:invalid` should be aliases for `.nes-input.is-success` and `.nes-input.is-error`.

**Describe alternatives you've considered**
* JS library, which is unnecessary (and possibly unwanted) in situations where you're leaning into HTML5 vanilla features
* Copying into my CSS, which is a lot of fairly opaque code (because of SVG embeds)

**Comment by BcRikko** [comment]
I like HTML5 validation ❤️ 
So I think this idea is good 👍 

But, Input fields always take the state `:valid` or `:invalid`.
Therefore, we will not be able to use the default color. 😭 
So we can't meet your request. 🙇 

```html
<input class="nes-input" type="url">
```
```css
.nes-input.is-success,
input.nes-input:valid {
  border: solid 4px #76c442;
  outline-color: #76c442;
}
.nes-input.is-success,
input.nes-input:invalid {
  border: solid 4px #ce372b;
  outline-color: #ce372b;
}
```
![nesinput](https://user-images.githubusercontent.com/5305599/62992957-70e2f180-be90-11e9-99be-7fee0f6630e5.gif)
