### ISSUE TITLE
Vertical Centering Support

### ISSUE THREAD

**Issue by GreXLin85** [nostalgic-css/NES.css#411]
Hello I want to make my `nes-container` vertical centered. I tried `vertical-align: middle;` but nothing changes, what can I do?

**Comment by BcRikko** [comment]
Sorry. I can't give you an answer because I don't know your situation in detail.
For general CSS tips, try using a flexbox. 👍 

```html
<div class="nes-container with-title">
  <span class="title">vertical align</span>
  <div class="vertical-center">
    ...your content
  </div>
</div>
```
```css
.vertical-center {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
}
```
