### ISSUE TITLE
Pixelated image rendering doesn't work on Firefox

### ISSUE THREAD

**Issue by makew0rld** [nostalgic-css/NES.css#447]
Follow up from #259.

**Describe the bug**

Using `image-rendering: pixelated` doesn't work on Firefox, but it's recommended on the home page.

**To Reproduce**

Look at the home page avatars on Firefox.

**Expected behavior**

It renders as pixelated.

**Screenshots**

![image](https://user-images.githubusercontent.com/25111343/106401145-88999700-63f0-11eb-88b9-1026ebf4b3bd.png)

**Suggestion(s) for fixing this issue**

Do something like this instead:

```css
.pixelated {
    image-rendering:optimizeSpeed;             /* Legal fallback */
    image-rendering:-moz-crisp-edges;          /* Firefox        */
    image-rendering:-o-crisp-edges;            /* Opera          */
    image-rendering:-webkit-optimize-contrast; /* Safari         */
    image-rendering:optimize-contrast;         /* CSS3 Proposed  */
    image-rendering:crisp-edges;               /* CSS4 Proposed  */
    image-rendering:pixelated;                 /* CSS4 Proposed  */
    -ms-interpolation-mode:nearest-neighbor;   /* IE8+           */
}
```

Source: https://news.ycombinator.com/item?id=25644485

**Comment by Ruedii** [comment]
For me it isn't quite that blurry but still antialiases.

I suspect rendering varies by platform and video drivers.

**Comment by RickMeasham** [comment]
This issue looks like it will be fixed by PR https://github.com/nostalgic-css/NES.css/pull/446

**Comment by makew0rld** [comment]
```css
.pixelated {
    image-rendering: -moz-crisp-edges;
    image-rendering: pixelated;                 /* CSS4 Proposed  */
    -ms-interpolation-mode: nearest-neighbor;   /* IE8+           */
}
```

This supports Firefox, Chrome, Opera, Safari, and IE8+. All the ones I mentioned originally weren't needed. This is what #446 does, although it has an additional line for really old (unneeded IMO) Safari support.
