### ISSUE TITLE
Broken graphics on Blink browsers

### ISSUE THREAD

**Issue by SilentImp** [nostalgic-css/NES.css#513]
**Describe the bug**

It seems that icons and some other elements somehow broken in brave.
There are spacing between "pixels" in the icons.

**To Reproduce**
1. Got to 'https://nostalgic-css.github.io/NES.css/' in the Brave browser
2. Icons look broken

**Expected behavior**

Icon without white spacing between "pixels"

**Screenshots**

***Brave (incorrect)***
<img width="758" alt="image" src="https://github.com/user-attachments/assets/7aee127e-1eec-42db-8c53-ffdceceec23c">

***Chrome Canary (incorrect)***
<img width="755" alt="image" src="https://github.com/user-attachments/assets/28d4141c-145e-4c6f-bc09-979061c8fb2a">

***Firefox (correct)***
<img width="759" alt="image" src="https://github.com/user-attachments/assets/09b55570-e5a9-4fc8-b4d7-c4bf1065a11f">

**Environment:**
 - OS: Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)
 - Browser: Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)
 - Build environment (i.e. NodeJS): 

**Suggestion(s) for fixing this issue**

**Additional context**

**Comment by SilentImp** [comment]
Maybe related to https://github.com/nostalgic-css/NES.css/issues/434
But 
```css
* {
    border-image-repeat: stretch !important;

    // for chrome
    @media all and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm) {
      border-image-repeat: stretch  !important;
    }
  
    // for firefox
    @supports (-moz-appearance: meterbar) {
      border-image-repeat: stretch  !important;
    }
}


```
doesn't seem helping
